export const content: string;
export const form: string;
export const formContainer: string;
export const heroHeader: string;
export const heroImg: string;
export const inlineForm: string;
export const logo: string;
export const signupContainer: string;
export const verticalForm: string;
