export const downloadBtn: string;
export const headerBtns: string;
export const icon: string;
export const imgMeta: string;
export const imgModal: string;
export const metaInfo: string;
export const modalContent: string;
export const modalFooter: string;
export const modalHeader: string;
