/**
 * This file is generated by @shopee-isfe/api-toolkit https://npm.shopee.io/-/web/detail/@shopee-isfe/api-toolkit
 */
/** NOT RECOMMENDED TO MODIFY */
import { createRequester, BODY_TYPE } from "./utils";
import { clientInit } from "./responseHandler";
export type DQueueConstant = object;

/**
 * Utility messages
 */
export interface DqueueResponseHeader {
  debug_msg?: string;
}

export const DEFAULT_BASE_URL = "/dqueue";

type Options = {
  fetch?: (input: RequestInfo, init?: RequestInit) => Promise<any>;
  requestInit?: RequestInit | (() => RequestInit);
  transformRequest?: <T = any>(
    path: string,
    method: string,
    body: any,
    bodyType?: BODY_TYPE,
    requestInit?: RequestInit
  ) => [T, RequestInit | undefined];
};

export type TestApiRequest = {};

export type TestApiResponse = {
  data?: TestApiResponseData;
};

export type TestApiResponseData = {
  name?: string;
};

export function getApis(baseUrl = DEFAULT_BASE_URL, opts?: Options) {
  const _request = createRequester({
    request: opts?.fetch,
    requestInit: opts?.requestInit,
  });
  let request = _request;
  if (opts?.transformRequest) {
    request = <
      Req extends { [key: string]: any } | null | undefined | void,
      Res,
      Rej = any
    >(
      path: string,
      method: string,
      body: any,
      bodyType?: BODY_TYPE,
      requestInit?: RequestInit
    ) => {
      /* Hack to pass TS compilier */
      const [_body, _requestInit] = opts?.transformRequest
        ? opts.transformRequest<Req>(path, method, body, bodyType, requestInit)
        : [body, requestInit];
      return _request<Req, Res, Rej>(
        path,
        method,
        _body,
        bodyType,
        _requestInit
      );
    };
  }

  const clients = {
    testApi: {
      path: "/test_api",
      post:
        /**
         * POST /test_api
         */
        (data: TestApiRequest, requestInit?: RequestInit) => {
          const path = "/test_api";
          return request<TestApiRequest, TestApiResponse>(
            baseUrl + path,
            "post",
            data,
            BODY_TYPE.json,
            requestInit
          );
        },
    }
  };
  return clients;
}

export const request = getApis(DEFAULT_BASE_URL, clientInit);
